<?php require_once "./template/header.html" ?>


<!--cover w/ skrollr values (for example data-100 for styles at 100 pixels scroled)-->
<div class="logocon" data-0="opacity: 1; display: flex" data-99="opacity: 0; display: none" data-100="display: none">
  <div class="logo animated fadeIn">City Whizz</div>
</div>
<div class="hint" data-0="bottom: 10vh" data-100="bottom: -25px"><a class="btn btn-danger lg"href="./login.phtml">Login</a></div>
<!--page contents below-->
<div class="menu"></div>

<?php require_once "./template/footer.html" ?>
