<?php require_once "./template/header.html" ?>
<div class="row">
  <div class="container" id="login">
    <img src="./assets/images/train.png" class="col-md-6 col-xs-12" alt="">
<div class="col-xs-12 col-md-6">
          <div class="form-group">
              <label for="email" class="col-xs-10 control-label">User Name</label>

              <div class="">
                  <input id="email" class="form-control col-xs-6" name="Username" value="">
                      <span class="help-block">
                          <strong></strong>
                      </span>

              </div>
          </div>

          <div class="form-group">
              <label for="password" class="col-xs-10 control-label">Password</label>

                  <input id="password" type="password" class="form-control" name="Password">

          </div>
<br>
                  <a type="submit" href="./journey.php" class="btn btn-info Brown">Login
                  </a>
                  <a href="./register.phtml" class="btn btn-warning Brown">Sign Up!</a>

</div>
  </div>
</div>

<?php require_once "./template/footer.html" ?>
