<?php require_once "./template/header.html" ?>

<div class="row">
  <div class="container" id="login">

<div class="col-xs-12 col-md-6 col-md-offset-3">
          <div class="form-group">
              <label for="email" class="col-xs-10 control-label black">User Name</label>

              <div class="">
                  <input id="email" class="form-control col-xs-6" name="Username" value="">
                      <span class="help-block">
                          <strong></strong>
                      </span>

              </div>
          </div>

          <div class="form-group">
              <label for="password" class="col-xs-10 control-label black">Password</label>

                  <input id="password" type="password" class="form-control" name="Password">

          </div>
          <br>
                  <a type="submit" href="./Login.phtml" class="btn btn-info">Sign Up
                  </a>
                  <a href="./Login.phtml" class="btn btn-warning">Login</a>

</div>
  </div>
</div>


<?php require_once "./template/footer.html" ?>
